FROM  registry.cn-hangzhou.aliyuncs.com/denverdino/tensorflow:1.0.0-devel

# for VPC, please use mirrors.cloud.aliyuncs.com, public cloud for mirrors.aliyun.com
RUN  sed -i 's/archive.ubuntu.com/mirrors.cloud.aliyuncs.com/' /etc/apt/sources.list
RUN  apt-get update && apt-get install -y git
RUN  mkdir /starter
COPY ./train_with_git.sh /starter
WORKDIR /starter
RUN  chmod +x train_with_git.sh
ENTRYPOINT ["./train_with_git.sh"]
